#! /bin/sh
# Script para golpear en Konversation.  Uso: “/exec golpear <víctima”.

SERVIDOR=$1
DESTINO=$2
shift 2

FRASES="$HOME/Development/konversation/fortune/archco"
VICTIMA="$@"
MENSAJE="/me golpea a $VICTIMA $(fortune $FRASES)"

qdbus org.kde.konversation /irc say $SERVIDOR $DESTINO "$MENSAJE"
